- src: robertdebock.bootstrap
  version: 4.6.2
- src: robertdebock.core_dependencies
  version: 4.6.2
- src: robertdebock.java
  version: 4.6.2
- src: geerlingguy.mysql
  version: 3.3.0
- src: geerlingguy.nginx
  version: 2.8.0
- src: derjd.journald
  version: 0.0.1
# - src: geerlingguy.certbot
#   version: 3.1.0