#!/bin/sh
# Copyright (C) 2004, International Business Machines Corporation
#  and others.  All Rights Reserved.
#
######################
##
## See documentation at: http://www.jtcsv.com/cgibin/cldrwiki.pl?CldrTools
##
######################
#
# To use: put this in your 'bin' dir, 
# and symlink it to XMLValidator and LDML2ICUConverter
#


## Change the following if needed
# where icu4j lives (or other classes)
CLDRCLASSPATH=${HOME}/icu4j/icu4j.jar:${HOME}/icu4j/classes/
# the command to use with java (or empty for none)
CPCMD=
# how to run java
JAVA=java

## Override the above settings in a ~/.cldrrc file if desired (+x)
# example:
#   CLDRCLASSPATH=${HOME}/J/icu4j/classes
if [ -x ${HOME}/.cldrrc ];
then
    . ${HOME}/.cldrrc
fi

if [ "x${CLDRCLASSPATH}" != "x" ];
then
  if [ "x${CPCMD}" = "x" ];
  then
      CPCMD="-classpath ${CLDRCLASSPATH}"
  fi
fi

## no need to change below this line. 
# base package 
PKG=com.ibm.icu.dev.tool.cldr
# root name of this script
ME=`basename $0`

if [ $ME = "CLDRWrapper" ];
then
    echo "# $ME: Don't run this script directly."
    echo Symlink $0 to the names XMLValidator, LDML2ICUConverter, and other ${PKG} tools.
    exit 1
fi

exec ${JAVA} ${CWDEFS} ${CPCMD} ${PKG}.${ME} $@
