services:
  site:
    build: .
    command: jekyll serve -s /src -d /tmp -p 4000 --watch
    ports:
    - 4000:4000
    volumes:
      - ../../../../docs/site:/src:rw
      - ./_site/:/_site:rw
    environment:
      - PAGES_REPO_NWO=unicode-org/cldr
