services:
  site:
    build: .
    command: jekyll serve -s /src -d /tmp -p 4000 --watch
    ports:
    - 4000:4000
    volumes:
      - ../../../../docs/site:/src:rw
      - ./_site/:/_site:rw
    environment:
      - PAGES_REPO_NWO=unicode-org/cldr
  build:
    image: node
    working_dir: /site
    command: /bin/sh -c 'npm ci ; npm run watch'
    volumes:
      - ../../../../docs/site:/site:rw

