package org.unicode.cldr.tool;

import com.google.common.collect.Multimap;
import com.google.common.collect.TreeMultimap;
import com.ibm.icu.text.DateTimePatternGenerator;
import java.util.Collection;
import java.util.Iterator;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import org.unicode.cldr.util.CLDRConfig;
import org.unicode.cldr.util.CLDRFile;
import org.unicode.cldr.util.CLDRLocale;
import org.unicode.cldr.util.DatetimeUtilities;
import org.unicode.cldr.util.DatetimeUtilities.DatePatternInfo;
import org.unicode.cldr.util.DatetimeUtilities.PatternElement;
import org.unicode.cldr.util.Level;
import org.unicode.cldr.util.Organization;
import org.unicode.cldr.util.StandardCodes;
import org.unicode.cldr.util.SupplementalDataInfo;
import org.unicode.cldr.util.XPathParts;

/**
 * Find all the missing available / interval formats that can be generated, and produce
 * modify_config file lines for them.
 */
public class FindCoverageFixes {
    static CLDRConfig CONFIG = CLDRConfig.getInstance();
    private static final SupplementalDataInfo SUPPLEMENTAL_DATA_INFO =
            CONFIG.getSupplementalDataInfo();

    public static void main(String[] args) {
        System.out.println("# Generated by FindCoverageFixes");
        for (String locale : StandardCodes.make().getLocaleCoverageLocales(Organization.cldr)) {
            CLDRLocale cldrLocale = CLDRLocale.getInstance(locale);
            if (!CLDRLocale.ROOT.equals(cldrLocale.getParent())) { // only top-level
                continue;
            }
            CLDRFile cldrFile = CONFIG.getCldrFactory().make(cldrLocale.toString(), false);

            // find out which availableFormat and intervalFormat are missing

            // First, find all the formats for the locale that have at least one path

            Multimap<String, XPathParts> calendarsWithMissingPaths =
                    findCalendarsWithMissingPaths(locale, cldrFile);
            if (calendarsWithMissingPaths.isEmpty()) {
                continue;
            }

            // we switch to resolved to get the full information

            CLDRFile cldrFileResolved = CONFIG.getCldrFactory().make(locale.toString(), true);
            Map<String, DatePatternInfo> calendarToDatePatternInfo =
                    DatetimeUtilities.calendarToDatePatternInfo(cldrFileResolved);

            for (Entry<String, Collection<XPathParts>> entry :
                    calendarsWithMissingPaths.asMap().entrySet()) {
                String calendar = entry.getKey();
                Collection<XPathParts> missingPaths = entry.getValue();
                DatePatternInfo dpi = calendarToDatePatternInfo.get(calendar);

                for (XPathParts parts : missingPaths) {
                    String formatType = parts.getElement(5);
                    switch (formatType) {
                        case "availableFormats":
                            String key = parts.getAttributeValue(6, "id");
                            DateTimePatternGenerator generator =
                                    dpi.getGenerator(false); // false = no stock
                            String newPattern = generator.getBestPattern(key);
                            XPathParts newParts = parts.cloneAsThawed();
                            newParts.setAttribute(-1, "draft", "contributed");
                            showRelated(dpi, key);
                            System.out.println(
                                    "locale="
                                            + locale
                                            + ";	action=add"
                                            + ";	new_path="
                                            + newParts
                                            + ";    new_value="
                                            + newPattern);
                            break;
                        case "intervalFormats":
                            // we don't have any interval formats missing this release, so wait on
                            // this.
                            throw new IllegalArgumentException(
                                    "FLESH OUT CODE FOR intervalFormats");
                            //                        switch (parts.getElement(6)) {
                            //                            case "intervalFormatItem":
                            //
                            // skeletonToGreatestDifferenceToPattern.put(
                            //                                        parts.getAttributeValue(6,
                            // "id"),
                            //                                        parts.getAttributeValue(7,
                            // "id"),
                            //                                        value);
                            //                                return;
                            //                            default:
                            //                                return;
                            //                        }
                            //                        break;
                    }
                }
            }
        }
    }

    private static void showRelated(DatePatternInfo dpi, String key) {
        Map<String, String> appendItems = dpi.getAvailableSkeletonToPattern();
        StringBuilder sb = new StringBuilder();
        for (Entry<String, String> entry : appendItems.entrySet()) {
            String skeleton = entry.getKey();
            String pattern = entry.getValue();
            if (isSimilar(key, skeleton)) {
                if (sb.length() > 0) {
                    sb.append(" ;\t ");
                }
                sb.append(skeleton + " → " + pattern);
            }
        }
        if (sb.length() != 0) {
            System.out.println("\n# Related items:\t" + sb);
        }
    }

    private static boolean isSimilar(String key, String skeleton) {
        Set<PatternElement> keyFields = DatetimeUtilities.getSkeletonElements(key);
        Set<PatternElement> skeletonFields = DatetimeUtilities.getSkeletonElements(skeleton);
        if (keyFields.size() != skeletonFields.size()) {
            return false;
        }
        Iterator<PatternElement> it1 = keyFields.iterator();
        Iterator<PatternElement> it2 = skeletonFields.iterator();
        while (it1.hasNext()) {
            PatternElement pe1 = it1.next();
            PatternElement pe2 = it2.next();
            if (pe1.getType() != pe2.getType()) {
                return false;
            }
            if (pe1.isNumeric() != pe2.isNumeric()) {
                return false;
            }
        }
        return true;
    }

    private static Multimap<String, XPathParts> findCalendarsWithMissingPaths(
            String locale, CLDRFile cldrFile) {
        // ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/availableFormats/dateFormatItem[@id="hms"]   h:mm:ss a
        // ldml/dates/calendars/calendar[@type="gregorian"]/dateTimeFormats/dateTimeFormatLength[@type="full"]/dateTimeFormat[@type="relative"]/pattern[@type="standard"]    {1} 'at' {0}

        Multimap<String, XPathParts> calendarToFormats = TreeMultimap.create();
        for (String path : cldrFile.fullIterable()) {

            XPathParts parts = XPathParts.getFrozenInstance(path);
            if (parts.size() < 6 || !parts.getElement(3).equals("calendar")) {
                continue;
            }

            Level level = SUPPLEMENTAL_DATA_INFO.getCoverageLevel(path, locale);
            if (level.compareTo(Level.MODERN) > 0) {
                continue;
            }

            // skip existing paths
            if (cldrFile.getStringValue(path) != null) {
                continue;
            }
            String calendar = parts.getAttributeValue(3, "type");
            String formatType = parts.getElement(5);
            switch (formatType) {
                case "availableFormats":
                case "intervalFormats":
                    calendarToFormats.put(calendar, parts);
                    break;
            }
        }
        return calendarToFormats;
    }
}
