package org.unicode.cldr.tool;

import java.io.PrintStream;
import java.util.TreeSet;
import java.util.regex.Pattern;

import org.unicode.cldr.util.CLDRTool;
import org.unicode.cldr.util.PatternCache;

import com.ibm.icu.dev.tool.UOption;

@CLDRTool(alias = "kbd", description = "Tool for working with CLDR Keyboard files")
public class KeyboardTool {

    private static final UOption[] options = {
        UOption.HELP_H(),
        UOption.HELP_QUESTION_MARK(),
        UOption.create("flatten", 'F', UOption.REQUIRES_ARG),
        UOption.create("implied-keys", 'I', UOption.NO_ARG),
    };

    public static void help() {
        System.out.println("CLDR Keyboard Tool\n" +
            "----\n" +
            "Usage:\n" +
            " -h | --help | -?                          print this help\n" +
            " -F infile.xml | --flatten infile.xml > outfile.xml      print a flattened xml to stdout, without imports\n" +
            " -I | --implied-keys                       Update keyboards/import/keys-Latn-implied.xml\n" +
            "");
    }

    public static void main(String args[]) throws Throwable {
        UOption.parseArgs(args, options);
        if (options[0].doesOccur || options[1].doesOccur) {
            help();
        } else if(options[2].doesOccur) {
            System.err.println("Flatten: " + options[2].value);
            KeyboardFlatten.flatten(options[2].value, System.out);
        } else if (options[3].doesOccur) {
            printImpliedKeys(System.out);
        } else {
            help();
        }
    }

    public static void printImpliedKeys(PrintStream out) {
        out.println("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                        "<!-- GENERATED by KeyboardTool. This is the implied import for implied keys. -->\n" +
                        "<!DOCTYPE keys SYSTEM \"../dtd/ldmlKeyboard.dtd\">\n" +
                        "<keys>\n");

        // add keys
        final String keyString = "`1234567890-=" +
                                 "qwertyuiop[]\\" +
                                 "asdfghjkl;'" +
                                 "zxcvbnm,./" +
                                 "~!@#$%^&*()_+" +
                                 "QWERTYUIOP{}" +
                                 "ASDFGHJKL:\"" +
                                 "ZXCVBNM<>?";
        final TreeSet<String> strs = new TreeSet<String>();
        for(final String s : keyString.split("")) {
            strs.add(s);
        }

        final Pattern p = PatternCache.get("[a-zA-Z0-9]");

        for(final String s : strs) {
            if(!needsEscape(s) && p.matcher(s).matches()) {
                out.println("<key id=\"" + s + "\" to=\"" + s + "\"/>");
            }
        }

        out.println("</keys>\n");
    }

    public static boolean needsEscape(String s) {
        if (s.equals("\"") || s.equals("&")) {
            return true;
        }
        return false;
    }
}
