# from https://en.wikibooks.org/wiki/SPARQL/Prefixes
PREFIX wd: <https://www.wikidata.org/entity/>
PREFIX wds: <https://www.wikidata.org/entity/statement/>
PREFIX wdv: <https://www.wikidata.org/value/>
PREFIX wdt: <https://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <https://www.wikidata.org/prop/>
PREFIX ps: <https://www.wikidata.org/prop/statement/>
PREFIX pq: <https://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bd: <http://www.bigdata.com/rdf#>

SELECT DISTINCT ?lang ?langCode WHERE {
  {
      ?lang wdt:P305 ?langCode. #langcode is IETF = BC47 code
  }
}
ORDER BY ?lang
