package org.unicode.cldr.web;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.json.JSONException;
import org.unicode.cldr.util.VettingViewer;

public class SurveyTool extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    public final void init(final ServletConfig config) throws ServletException {
        System.out.println("\n🍓🍓🍓 SurveyTool.init() 🍓🍓🍓\n");
        try {
            super.init(config);
        } catch (Throwable t) {
            System.err.println("SurveyTool.init() caught: " + t.toString());
            return;
        }
    }

    @Override
    public void service(ServletRequest request, ServletResponse response) throws ServletException, IOException {
        serveSinglePageApp((HttpServletRequest) request, (HttpServletResponse) response);
    }

    /**
     * Serve the HTML for Survey Tool
     *
     * @param request
     * @param response
     * @throws IOException
     *
     * Serve four different versions of the html page:
     *   1. Busted/Offline
     *   2. Starting/Waiting
     *   3. Problem (session==null)
     *   4. Running normally
     *
     * TODO: reduce html dynamically generated by back end (Java); leave presentation to be done by the front end (JavaScript)
     */
    private void serveSinglePageApp(HttpServletRequest request, HttpServletResponse response) throws IOException {
        SurveyMain sm = SurveyMain.getInstance(request);
        PrintWriter out = response.getWriter();
        out.write("<!DOCTYPE html>\n");
        if (SurveyMain.isBusted != null || request.getParameter("_BUSTED") != null) {
            serveBustedPage(request, out);
        } else if (sm == null || !SurveyMain.isSetup || request.getParameter("_STARTINGUP") != null) {
            serveWaitingPage(request, out, sm);
        } else {
            WebContext ctx = new WebContext(request, response);
            request.setAttribute("WebContext", ctx);
            String status = ctx.setSession();
            if (ctx.session == null) {
                serveProblemNoSessionPage(request, out, status);
            } else {
                serveRunnningNormallyPage(request, out, sm);
            }
        }
    }

    private void serveBustedPage(HttpServletRequest request, PrintWriter out) {
        out.write("<html>\n<head>\n");
        out.write("<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>\n");
        out.write("<title>CLDR Survey Tool | Offline</title>\n");
        includeCss(request, out);
        out.write("</head>\n<body>\n");
        out.write("<p class='ferrorbox'>Survey Tool is offline</p>\n");
        out.write("</body>\n</html>\n");
    }

    private void serveWaitingPage(HttpServletRequest request, PrintWriter out, SurveyMain sm)
            throws IOException {
        String url = request.getContextPath() + request.getServletPath();
        out.write("<html lang='" + SurveyMain.TRANS_HINT_LOCALE.toLanguageTag() + " class='claro'>\n");
        out.write("<head>\n");
        out.write("<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>\n");
        out.write("<title>CLDR Survey Tool | Starting</title>\n");
        includeCss(request, out);
        if (request.getParameter("_STARTINGUP") == null) {
            writeTimeoutReloadScript(out, url);
        }
        writeDotDotDotScript(out);
        out.write(VettingViewer.getHeaderStyles() + "\n");
        try {
            SurveyAjax.includeJavaScript(request, out);
        } catch (JSONException e) {
            SurveyLog.logException(e, "Including JavaScript");
        }
        out.write("</head>\n<body>\n");
        writeWaitingNavbarHtml(out);

        out.write("<div class='container'>\n");
        out.write("  <div class='starter-template' style='margin-top: 120px;'>\n");

        out.write("<h1>Waiting for the Survey Tool to come online<span id='dots'>...</span></h1>\n");
        out.write("<p class='lead'>The Survey Tool may be starting up.  </p>\n");
        if (SurveyMain.isUnofficial()) {
            out.write("<p><span class='glyphicon glyphicon-wrench'></span>"
                + SurveyMain.getCurrev(true) + "</p>\n");
        }
        out.write("If you are not redirected in a minute or two, please click\n");
        out.write("<a id='redir2' href='" + request.getContextPath() + "/survey"
            + "'>this link</a> to try again.\n");
        /***
         * TODO: more code here from v.jsp...
        if (request.getParameter("_STARTINGUP") == null) {
            out.write("<script>\n");
            ...
            out.write("</script>\n");
        }
        ***/

        if (sm != null) {
            String htmlStatus = sm.startupThread.htmlStatus();
            if (htmlStatus != null) {
                out.write(htmlStatus);
            }
        }
        out.write("<hr>\n");
        out.write("<div id='st_err'></div>\n</div>\n</div>\n");
        out.write("</body>\n</html>\n");
    }

    private void writeTimeoutReloadScript(PrintWriter out, String url) {
        out.write("<script>\n");
        out.write("  window.setTimeout(function() {\n");
        out.write("    window.location.reload(true);\n");
        out.write("    //document.location='" + url
                    + "' + document.location.search + document.location.hash;\n");
        out.write("  },10000 /* ten seconds */);\n");
        out.write("</script>\n");
    }

    private void writeDotDotDotScript(PrintWriter out) {
        out.write("<script>\n");
        out.write("var spin0 = 0;\n");
        out.write("window.setInterval(function() {\n");
        out.write("    spin0 = (spin0+1)%3;\n");
        out.write("    var dots = document.getElementById('dots');\n");
        out.write("    if (dots) {\n");
        out.write("        switch(spin0) {\n");
        out.write("         case 0:\n");
        out.write("             dots.innerHTML = '.';\n");
        out.write("             break;\n");
        out.write("         case 1:\n");
        out.write("             dots.innerHTML='&nbsp;.';\n");
        out.write("             break;\n");
        out.write("         case 2:\n");
        out.write("            dots.innerHTML='&nbsp;&nbsp;.';\n");
        out.write("           break;\n");
        out.write("        }\n");
        out.write("    }\n");
        out.write("}, 1000);\n");
        out.write("</script>\n");
    }

    private void writeWaitingNavbarHtml(PrintWriter out) {
        out.write("<div class=\"navbar navbar-fixed-top\" role=\"navigation\">\n"
            + "  <div class=\"container\">\n"
            + "    <div class=\"navbar-header\">\n"
            + "      <p class=\"navbar-brand\">\n"
            + "        <a href=\"http://cldr.unicode.org\">CLDR</a> SurveyTool\n"
            + "      </p>\n"
            + "    </div>\n"
            + "    <div class=\"collapse navbar-collapse  navbar-right\">\n"
            + "      <ul class=\"nav navbar-nav\">\n"
            + "        <li><a href=\"http://cldr.unicode.org/index/survey-tool\">Help</a></li>\n"
            + "      </ul>\n"
            + "    </div>\n"
            + "  </div>\n"
            + "</div>\n");
    }

    private void serveProblemNoSessionPage(HttpServletRequest request, PrintWriter out, String status) {
        out.write("<html class='claro'>\n<head class='claro'>\n");
        out.write("<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>\n");
        out.write("<title>CLDR Survey Tool</title>\n");
        out.write("</head>\n<body>\n");
        out.write("<p class='ferrorbox'>Survey Tool is offline</p>\n");
        out.write("<div style='float: right'>\n");
        out.write("  <a href='" + request.getContextPath() + "/login.jsp'"
            + " id='loginlink' class='notselected'>Login…</a>\n");
        out.write("</div>\n");
        out.write("<h2>CLDR Survey Tool | Problem</h2>\n");
        out.write("<div>\n");
        out.write("<p><img src='stop.png' width='16'>" + status + "</p>\n");
        out.write("</div>\n");
        out.write("<hr>\n");
        out.write("<p><" + SurveyMain.getGuestsAndUsers() + "</p>\n");
        out.write("</body>\n</html>\n");
    }

    private void serveRunnningNormallyPage(HttpServletRequest request, PrintWriter out, SurveyMain sm)
            throws IOException {
        String lang = SurveyMain.TRANS_HINT_LOCALE.toLanguageTag();
        out.write("<html lang='" + lang + "' class='claro'>\n");
        out.write("<head>\n");
        out.write("<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>\n");
        out.write("<title>CLDR Survey Tool</title>\n");
        out.write("<meta name='robots' content='noindex,nofollow'>\n");
        out.write("<meta name='gigabot' content='noindex'>\n");
        out.write("<meta name='gigabot' content='noarchive'>\n");
        out.write("<meta name='gigabot' content='nofollow'>\n");
        includeCss(request, out);
        out.write(VettingViewer.getHeaderStyles() + "\n");
        try {
            SurveyAjax.includeJavaScript(request, out);
        } catch (JSONException e) {
            SurveyLog.logException(e, "Including JavaScript");
        }
        out.write("</head>\n");
        out.write("<body lang='" + lang + " data-spy='scroll' data-target='#itemInfo'>\n");
        out.write("Loading...\n");
        out.write("</body>\n</html>\n");
    }

    private void includeCss(HttpServletRequest request, PrintWriter out) {
        String contextPath = request.getContextPath();
        out.write("<link rel='stylesheet' href='" + contextPath + "/surveytool.css' />\n");
        out.write("<link rel='stylesheet' href='" + contextPath + "/css/CldrStForum.css' />\n");
        out.write("<link rel='stylesheet' href='//ajax.googleapis.com/ajax/libs/dojo/1.14.1/dijit/themes/claro/claro.css' />\n");
        out.write("<link rel='stylesheet' href='//stackpath.bootstrapcdn.com/bootswatch/3.1.1/spacelab/bootstrap.min.css' />\n");
        out.write("<link rel='stylesheet' href='" + contextPath + "/css/redesign.css' />\n");
    }
}
