name: CLDR LDML
title: CLDR LDML

markdown: kramdown
input: GFM

destination: ../_site

# Google Analytics
ga_tracking: UA-7672775-1
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings

exclude:
  - charts/keyboards/node_modules
  - charts/keyboards/node
  - ldml

#include:
#  - site/

# _config.yml

# everything under 'site' should default to the 'page' layout
defaults:
  - scope:
      path: 'site'
    values:
      layout: page

collections:
  site:
    output: true
