name: Ansible Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: false # not needed for this job, as we don’t currently do a Java build
    - name: Lint Ansible Playbook
      # the hash here is a specific version of that repo, since there is not a later commit.
      uses: ansible/ansible-lint-action@6c8c14186662e43effbe39a678950896a46799ad
      with:
        targets: tools/scripts/ansible/*-playbook.yml
    - name: Lint Markdown
      # Warn, don't fail yet
      run: npx markdownlint-cli *.md {specs,docs}/*.md $(find .github -name '*.md') || (echo Warning, please fix these ; true)
    - name: Lint GitHub Actions
      run: npx yaml-lint .github/workflows/*.yml
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: false # not needed for this job, as we don’t currently do a Java build
    - name: Install Vagrant and Ansible
      run: brew install ansible
    - name: Try the provision
      run: cd tools/scripts/ansible && ansible-galaxy install -r roles.yml && ln -sv test-local-vars local-vars && vagrant up
