# .github/workflows/auto-author-assign.yml
name: SUMMER DAWN SMITH

on:
  pull_request_target:
    types: [ opened, reopened ]

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/SUMMER-DAWN-SMITH@v2.1.0
