#!/bin/bash
# this script is called by cldr-modify.yml in order to perform the commit.
#
# usage:  cldr-modify-commit.sh cldr-modify.yml CldrModify
set -euo pipefail
TOP_TICKET=$(git log -n 1 --pretty=%s HEAD | head -1 | cut -d' ' -f1)
if echo "${TOP_TICKET}" | egrep -q 'zCLDR-[0-9]+';
then
    echo "# Error, could not determine top ticket"
    git log -n 1 HEAD
    exit 1
fi
TOP_SHA=$(git log --pretty=%h -n 1 HEAD)

echo "- Most recent ticket: ${TOP_TICKET}"
set -x
exec git commit -am "${TOP_TICKET} $2 from ${TOP_SHA}

${TOP_TICKET}

 - This commit was generated by $1, see <https://cldr.unicode.org/development/auto-pr>"
