name: gh-pages

env:
  CLDR_DIR: ${{ github.workspace }}

# This publishes the 'rfc' section to github pages
# TODO: https://unicode-org.atlassian.net/browse/CLDR-19328 for more clarity on RFC

permissions:
  pages: write
  deployments: write
  id-token: write
  actions: read

on:
  push:
    branches:
      - main
    # Only run if rfc changes.
    paths:
      - "docs/rfc/**"
      - ".github/workflows/gh-pages.yml"
jobs:
  build:
    name: "Build Github Pages"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
      - name: Build Jekyll part of the site (not spec, not site/)
        run: |
          gem install bundler github-pages kramdown-parser-gfm  # should pull in jekyll, etc.
          cd docs &&  github-pages build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages (main)
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v4
