package com.macchiato.client;
// Fri Jan 30 12:41:53 PST 2009
public class CharData {
static String[][] CHARACTERS_TO_NAME = {
{" ","SPACE"},
{"-","HYPHEN-MINUS"},
{" ","NO-BREAK SPACE"},
{"­","SOFT HYPHEN"},
{"͏","COMBINING GRAPHEME JOINER"},
{"֊","ARMENIAN HYPHEN"},
{"־","HEBREW PUNCTUATION MAQAF"},
{"؀","ARABIC NUMBER SIGN"},
{"؁","ARABIC SIGN SANAH"},
{"؂","ARABIC FOOTNOTE MARKER"},
{"؃","ARABIC SIGN SAFHA"},
{"۝","ARABIC END OF AYAH"},
{"܏","SYRIAC ABBREVIATION MARK"},
{"ᅟ","HANGUL CHOSEONG FILLER"},
{"ᅠ","HANGUL JUNGSEONG FILLER"},
{" ","OGHAM SPACE MARK"},
{"឴","KHMER VOWEL INHERENT AQ"},
{"឵","KHMER VOWEL INHERENT AA"},
{"᠆","MONGOLIAN TODO SOFT HYPHEN"},
{"᠋","MONGOLIAN FREE VARIATION SELECTOR ONE"},
{"᠌","MONGOLIAN FREE VARIATION SELECTOR TWO"},
{"᠍","MONGOLIAN FREE VARIATION SELECTOR THREE"},
{"᠎","MONGOLIAN VOWEL SEPARATOR"},
{" ","EN QUAD"},
{" ","EM QUAD"},
{" ","EN SPACE"},
{" ","EM SPACE"},
{" ","THREE-PER-EM SPACE"},
{" ","FOUR-PER-EM SPACE"},
{" ","SIX-PER-EM SPACE"},
{" ","FIGURE SPACE"},
{" ","PUNCTUATION SPACE"},
{" ","THIN SPACE"},
{" ","HAIR SPACE"},
{"​","ZERO WIDTH SPACE"},
{"‌","ZERO WIDTH NON-JOINER"},
{"‍","ZERO WIDTH JOINER"},
{"‎","LEFT-TO-RIGHT MARK"},
{"‏","RIGHT-TO-LEFT MARK"},
{"‐","HYPHEN"},
{"‑","NON-BREAKING HYPHEN"},
{"‒","FIGURE DASH"},
{"–","EN DASH"},
{"—","EM DASH"},
{"―","HORIZONTAL BAR"},
{" ","LINE SEPARATOR"},
{" ","PARAGRAPH SEPARATOR"},
{"‪","LEFT-TO-RIGHT EMBEDDING"},
{"‫","RIGHT-TO-LEFT EMBEDDING"},
{"‬","POP DIRECTIONAL FORMATTING"},
{"‭","LEFT-TO-RIGHT OVERRIDE"},
{"‮","RIGHT-TO-LEFT OVERRIDE"},
{" ","NARROW NO-BREAK SPACE"},
{" ","MEDIUM MATHEMATICAL SPACE"},
{"⁠","WORD JOINER"},
{"⁡","FUNCTION APPLICATION"},
{"⁢","INVISIBLE TIMES"},
{"⁣","INVISIBLE SEPARATOR"},
{"⁤","INVISIBLE PLUS"},
{"⸗","DOUBLE OBLIQUE HYPHEN"},
{"⸚","HYPHEN WITH DIAERESIS"},
{"　","IDEOGRAPHIC SPACE"},
{"〜","WAVE DASH"},
{"〰","WAVY DASH"},
{"゠","KATAKANA-HIRAGANA DOUBLE HYPHEN"},
{"ㅤ","HANGUL FILLER"},
{"︀","VARIATION SELECTOR-1"},
{"︁","VARIATION SELECTOR-2"},
{"︂","VARIATION SELECTOR-3"},
{"︃","VARIATION SELECTOR-4"},
{"︄","VARIATION SELECTOR-5"},
{"︅","VARIATION SELECTOR-6"},
{"︆","VARIATION SELECTOR-7"},
{"︇","VARIATION SELECTOR-8"},
{"︈","VARIATION SELECTOR-9"},
{"︉","VARIATION SELECTOR-10"},
{"︊","VARIATION SELECTOR-11"},
{"︋","VARIATION SELECTOR-12"},
{"︌","VARIATION SELECTOR-13"},
{"︍","VARIATION SELECTOR-14"},
{"︎","VARIATION SELECTOR-15"},
{"️","VARIATION SELECTOR-16"},
{"︱","PRESENTATION FORM FOR VERTICAL EM DASH"},
{"︲","PRESENTATION FORM FOR VERTICAL EN DASH"},
{"﹘","SMALL EM DASH"},
{"﹣","SMALL HYPHEN-MINUS"},
{"﻿","ZERO WIDTH NO-BREAK SPACE"},
{"－","FULLWIDTH HYPHEN-MINUS"},
{"ﾠ","HALFWIDTH HANGUL FILLER"},
{"￹","INTERLINEAR ANNOTATION ANCHOR"},
{"￺","INTERLINEAR ANNOTATION SEPARATOR"},
{"￻","INTERLINEAR ANNOTATION TERMINATOR"},
{"𝅳","MUSICAL SYMBOL BEGIN BEAM"},
{"𝅴","MUSICAL SYMBOL END BEAM"},
{"𝅵","MUSICAL SYMBOL BEGIN TIE"},
{"𝅶","MUSICAL SYMBOL END TIE"},
{"𝅷","MUSICAL SYMBOL BEGIN SLUR"},
{"𝅸","MUSICAL SYMBOL END SLUR"},
{"𝅹","MUSICAL SYMBOL BEGIN PHRASE"},
{"𝅺","MUSICAL SYMBOL END PHRASE"},
{"󠄀","VARIATION SELECTOR-17"},
{"󠄁","VARIATION SELECTOR-18"},
{"󠄂","VARIATION SELECTOR-19"},
{"󠄃","VARIATION SELECTOR-20"},
{"󠄄","VARIATION SELECTOR-21"},
{"󠄅","VARIATION SELECTOR-22"},
{"󠄆","VARIATION SELECTOR-23"},
{"󠄇","VARIATION SELECTOR-24"},
{"󠄈","VARIATION SELECTOR-25"},
{"󠄉","VARIATION SELECTOR-26"},
{"󠄊","VARIATION SELECTOR-27"},
{"󠄋","VARIATION SELECTOR-28"},
{"󠄌","VARIATION SELECTOR-29"},
{"󠄍","VARIATION SELECTOR-30"},
{"󠄎","VARIATION SELECTOR-31"},
{"󠄏","VARIATION SELECTOR-32"},
{"󠄐","VARIATION SELECTOR-33"},
{"󠄑","VARIATION SELECTOR-34"},
{"󠄒","VARIATION SELECTOR-35"},
{"󠄓","VARIATION SELECTOR-36"},
{"󠄔","VARIATION SELECTOR-37"},
{"󠄕","VARIATION SELECTOR-38"},
{"󠄖","VARIATION SELECTOR-39"},
{"󠄗","VARIATION SELECTOR-40"},
{"󠄘","VARIATION SELECTOR-41"},
{"󠄙","VARIATION SELECTOR-42"},
{"󠄚","VARIATION SELECTOR-43"},
{"󠄛","VARIATION SELECTOR-44"},
{"󠄜","VARIATION SELECTOR-45"},
{"󠄝","VARIATION SELECTOR-46"},
{"󠄞","VARIATION SELECTOR-47"},
{"󠄟","VARIATION SELECTOR-48"},
{"󠄠","VARIATION SELECTOR-49"},
{"󠄡","VARIATION SELECTOR-50"},
{"󠄢","VARIATION SELECTOR-51"},
{"󠄣","VARIATION SELECTOR-52"},
{"󠄤","VARIATION SELECTOR-53"},
{"󠄥","VARIATION SELECTOR-54"},
{"󠄦","VARIATION SELECTOR-55"},
{"󠄧","VARIATION SELECTOR-56"},
{"󠄨","VARIATION SELECTOR-57"},
{"󠄩","VARIATION SELECTOR-58"},
{"󠄪","VARIATION SELECTOR-59"},
{"󠄫","VARIATION SELECTOR-60"},
{"󠄬","VARIATION SELECTOR-61"},
{"󠄭","VARIATION SELECTOR-62"},
{"󠄮","VARIATION SELECTOR-63"},
{"󠄯","VARIATION SELECTOR-64"},
{"󠄰","VARIATION SELECTOR-65"},
{"󠄱","VARIATION SELECTOR-66"},
{"󠄲","VARIATION SELECTOR-67"},
{"󠄳","VARIATION SELECTOR-68"},
{"󠄴","VARIATION SELECTOR-69"},
{"󠄵","VARIATION SELECTOR-70"},
{"󠄶","VARIATION SELECTOR-71"},
{"󠄷","VARIATION SELECTOR-72"},
{"󠄸","VARIATION SELECTOR-73"},
{"󠄹","VARIATION SELECTOR-74"},
{"󠄺","VARIATION SELECTOR-75"},
{"󠄻","VARIATION SELECTOR-76"},
{"󠄼","VARIATION SELECTOR-77"},
{"󠄽","VARIATION SELECTOR-78"},
{"󠄾","VARIATION SELECTOR-79"},
{"󠄿","VARIATION SELECTOR-80"},
{"󠅀","VARIATION SELECTOR-81"},
{"󠅁","VARIATION SELECTOR-82"},
{"󠅂","VARIATION SELECTOR-83"},
{"󠅃","VARIATION SELECTOR-84"},
{"󠅄","VARIATION SELECTOR-85"},
{"󠅅","VARIATION SELECTOR-86"},
{"󠅆","VARIATION SELECTOR-87"},
{"󠅇","VARIATION SELECTOR-88"},
{"󠅈","VARIATION SELECTOR-89"},
{"󠅉","VARIATION SELECTOR-90"},
{"󠅊","VARIATION SELECTOR-91"},
{"󠅋","VARIATION SELECTOR-92"},
{"󠅌","VARIATION SELECTOR-93"},
{"󠅍","VARIATION SELECTOR-94"},
{"󠅎","VARIATION SELECTOR-95"},
{"󠅏","VARIATION SELECTOR-96"},
{"󠅐","VARIATION SELECTOR-97"},
{"󠅑","VARIATION SELECTOR-98"},
{"󠅒","VARIATION SELECTOR-99"},
{"󠅓","VARIATION SELECTOR-100"},
{"󠅔","VARIATION SELECTOR-101"},
{"󠅕","VARIATION SELECTOR-102"},
{"󠅖","VARIATION SELECTOR-103"},
{"󠅗","VARIATION SELECTOR-104"},
{"󠅘","VARIATION SELECTOR-105"},
{"󠅙","VARIATION SELECTOR-106"},
{"󠅚","VARIATION SELECTOR-107"},
{"󠅛","VARIATION SELECTOR-108"},
{"󠅜","VARIATION SELECTOR-109"},
{"󠅝","VARIATION SELECTOR-110"},
{"󠅞","VARIATION SELECTOR-111"},
{"󠅟","VARIATION SELECTOR-112"},
{"󠅠","VARIATION SELECTOR-113"},
{"󠅡","VARIATION SELECTOR-114"},
{"󠅢","VARIATION SELECTOR-115"},
{"󠅣","VARIATION SELECTOR-116"},
{"󠅤","VARIATION SELECTOR-117"},
{"󠅥","VARIATION SELECTOR-118"},
{"󠅦","VARIATION SELECTOR-119"},
{"󠅧","VARIATION SELECTOR-120"},
{"󠅨","VARIATION SELECTOR-121"},
{"󠅩","VARIATION SELECTOR-122"},
{"󠅪","VARIATION SELECTOR-123"},
{"󠅫","VARIATION SELECTOR-124"},
{"󠅬","VARIATION SELECTOR-125"},
{"󠅭","VARIATION SELECTOR-126"},
{"󠅮","VARIATION SELECTOR-127"},
{"󠅯","VARIATION SELECTOR-128"},
{"󠅰","VARIATION SELECTOR-129"},
{"󠅱","VARIATION SELECTOR-130"},
{"󠅲","VARIATION SELECTOR-131"},
{"󠅳","VARIATION SELECTOR-132"},
{"󠅴","VARIATION SELECTOR-133"},
{"󠅵","VARIATION SELECTOR-134"},
{"󠅶","VARIATION SELECTOR-135"},
{"󠅷","VARIATION SELECTOR-136"},
{"󠅸","VARIATION SELECTOR-137"},
{"󠅹","VARIATION SELECTOR-138"},
{"󠅺","VARIATION SELECTOR-139"},
{"󠅻","VARIATION SELECTOR-140"},
{"󠅼","VARIATION SELECTOR-141"},
{"󠅽","VARIATION SELECTOR-142"},
{"󠅾","VARIATION SELECTOR-143"},
{"󠅿","VARIATION SELECTOR-144"},
{"󠆀","VARIATION SELECTOR-145"},
{"󠆁","VARIATION SELECTOR-146"},
{"󠆂","VARIATION SELECTOR-147"},
{"󠆃","VARIATION SELECTOR-148"},
{"󠆄","VARIATION SELECTOR-149"},
{"󠆅","VARIATION SELECTOR-150"},
{"󠆆","VARIATION SELECTOR-151"},
{"󠆇","VARIATION SELECTOR-152"},
{"󠆈","VARIATION SELECTOR-153"},
{"󠆉","VARIATION SELECTOR-154"},
{"󠆊","VARIATION SELECTOR-155"},
{"󠆋","VARIATION SELECTOR-156"},
{"󠆌","VARIATION SELECTOR-157"},
{"󠆍","VARIATION SELECTOR-158"},
{"󠆎","VARIATION SELECTOR-159"},
{"󠆏","VARIATION SELECTOR-160"},
{"󠆐","VARIATION SELECTOR-161"},
{"󠆑","VARIATION SELECTOR-162"},
{"󠆒","VARIATION SELECTOR-163"},
{"󠆓","VARIATION SELECTOR-164"},
{"󠆔","VARIATION SELECTOR-165"},
{"󠆕","VARIATION SELECTOR-166"},
{"󠆖","VARIATION SELECTOR-167"},
{"󠆗","VARIATION SELECTOR-168"},
{"󠆘","VARIATION SELECTOR-169"},
{"󠆙","VARIATION SELECTOR-170"},
{"󠆚","VARIATION SELECTOR-171"},
{"󠆛","VARIATION SELECTOR-172"},
{"󠆜","VARIATION SELECTOR-173"},
{"󠆝","VARIATION SELECTOR-174"},
{"󠆞","VARIATION SELECTOR-175"},
{"󠆟","VARIATION SELECTOR-176"},
{"󠆠","VARIATION SELECTOR-177"},
{"󠆡","VARIATION SELECTOR-178"},
{"󠆢","VARIATION SELECTOR-179"},
{"󠆣","VARIATION SELECTOR-180"},
{"󠆤","VARIATION SELECTOR-181"},
{"󠆥","VARIATION SELECTOR-182"},
{"󠆦","VARIATION SELECTOR-183"},
{"󠆧","VARIATION SELECTOR-184"},
{"󠆨","VARIATION SELECTOR-185"},
{"󠆩","VARIATION SELECTOR-186"},
{"󠆪","VARIATION SELECTOR-187"},
{"󠆫","VARIATION SELECTOR-188"},
{"󠆬","VARIATION SELECTOR-189"},
{"󠆭","VARIATION SELECTOR-190"},
{"󠆮","VARIATION SELECTOR-191"},
{"󠆯","VARIATION SELECTOR-192"},
{"󠆰","VARIATION SELECTOR-193"},
{"󠆱","VARIATION SELECTOR-194"},
{"󠆲","VARIATION SELECTOR-195"},
{"󠆳","VARIATION SELECTOR-196"},
{"󠆴","VARIATION SELECTOR-197"},
{"󠆵","VARIATION SELECTOR-198"},
{"󠆶","VARIATION SELECTOR-199"},
{"󠆷","VARIATION SELECTOR-200"},
{"󠆸","VARIATION SELECTOR-201"},
{"󠆹","VARIATION SELECTOR-202"},
{"󠆺","VARIATION SELECTOR-203"},
{"󠆻","VARIATION SELECTOR-204"},
{"󠆼","VARIATION SELECTOR-205"},
{"󠆽","VARIATION SELECTOR-206"},
{"󠆾","VARIATION SELECTOR-207"},
{"󠆿","VARIATION SELECTOR-208"},
{"󠇀","VARIATION SELECTOR-209"},
{"󠇁","VARIATION SELECTOR-210"},
{"󠇂","VARIATION SELECTOR-211"},
{"󠇃","VARIATION SELECTOR-212"},
{"󠇄","VARIATION SELECTOR-213"},
{"󠇅","VARIATION SELECTOR-214"},
{"󠇆","VARIATION SELECTOR-215"},
{"󠇇","VARIATION SELECTOR-216"},
{"󠇈","VARIATION SELECTOR-217"},
{"󠇉","VARIATION SELECTOR-218"},
{"󠇊","VARIATION SELECTOR-219"},
{"󠇋","VARIATION SELECTOR-220"},
{"󠇌","VARIATION SELECTOR-221"},
{"󠇍","VARIATION SELECTOR-222"},
{"󠇎","VARIATION SELECTOR-223"},
{"󠇏","VARIATION SELECTOR-224"},
{"󠇐","VARIATION SELECTOR-225"},
{"󠇑","VARIATION SELECTOR-226"},
{"󠇒","VARIATION SELECTOR-227"},
{"󠇓","VARIATION SELECTOR-228"},
{"󠇔","VARIATION SELECTOR-229"},
{"󠇕","VARIATION SELECTOR-230"},
{"󠇖","VARIATION SELECTOR-231"},
{"󠇗","VARIATION SELECTOR-232"},
{"󠇘","VARIATION SELECTOR-233"},
{"󠇙","VARIATION SELECTOR-234"},
{"󠇚","VARIATION SELECTOR-235"},
{"󠇛","VARIATION SELECTOR-236"},
{"󠇜","VARIATION SELECTOR-237"},
{"󠇝","VARIATION SELECTOR-238"},
{"󠇞","VARIATION SELECTOR-239"},
{"󠇟","VARIATION SELECTOR-240"},
{"󠇠","VARIATION SELECTOR-241"},
{"󠇡","VARIATION SELECTOR-242"},
{"󠇢","VARIATION SELECTOR-243"},
{"󠇣","VARIATION SELECTOR-244"},
{"󠇤","VARIATION SELECTOR-245"},
{"󠇥","VARIATION SELECTOR-246"},
{"󠇦","VARIATION SELECTOR-247"},
{"󠇧","VARIATION SELECTOR-248"},
{"󠇨","VARIATION SELECTOR-249"},
{"󠇩","VARIATION SELECTOR-250"},
{"󠇪","VARIATION SELECTOR-251"},
{"󠇫","VARIATION SELECTOR-252"},
{"󠇬","VARIATION SELECTOR-253"},
{"󠇭","VARIATION SELECTOR-254"},
{"󠇮","VARIATION SELECTOR-255"},
{"󠇯","VARIATION SELECTOR-256"},

  };
  static String[][][] CATEGORIES = {
{{"Symbol"},
/*368,41*/ {"Arrows","←↚→↛↑↓↮↕↜↯⇐⇍⇑⇏⇓⇎⇕➔➘➱⟰⤀⤝⥱⬀⭐"},
/*65,18*/ {"CJK","〆〼〱⿰㇀〄〒〠〷〾㆐㉿"},
/*38,3*/ {"Control Pictures","␀␦"},
/*29,12*/ {"Currency","$؋৲૱௹฿៛₠₩"},
/*204,18*/ {"Game Pieces","☖♔⚀⛀⟘⫞🀀🀰"},
/*14,4*/ {"Gender and Genealogical","⚢⚭"},
/*256,2*/ {"Geometric Shapes","─"},
/*1,1*/ {"Greek And Coptic","ʹ"},
/*29,12*/ {"Keyboard and UI","⌚⌤⌫⎀⎖⏎␥"},
/*68,63*/ {"Latin","ꞈᵃᴬᵆᵄᵇᴮᵈᴰᵉᴱᵊᴳʰᴴʱᴵʲᴶᵏᴷᵐᴹᵑᴼᵓᴽᵖᴾʳᴿʴᵗᵀᵘᵁᵙʷᵂʸᵜ§¶©®°¬¦¤¢¥"},
/*17,17*/ {"Letterlike","℄℈℔℗℞℣℥℧℩℮℺⅊⅌⅏"},
/*676,141*/ {"Math","⁄⅋⁒؈⅁∀϶∎+÷×<≮=≠>≯|~−؆∜؇∝∮∱≁∽≂≇≆≈≭≎≡≰≥≱≦≲≴≳≵≸≷≹⊀≻⊁≼⋠≽⋡≾⊂⊄⊃⊅⊈⊇⊉⋢⊒⋣⊓⊬⊣⊭⊩⊮⊪⊯⋪⊳⋫⊴⋬⊵⋭⊶⋤⋮⌈⌠⎛⏜⟀⟇⟌⟐⟠⤙⥰⥼⦙⧜⧾⨍⩷⫝⫮"},
/*176,35*/ {"Miscellaneous","☎☕☘☸♈♨♰⚐⚠⚪✁✆✌✩❍❏❖❘❡�"},
/*176,30*/ {"Musical","♩𝄀♭𝄪𝄩𝄺𝅪𝆃𝆌𝆮𝇁"},
/*5,5*/ {"Subscript","ₐₔₒ"},
/*6,3*/ {"Superscript","ˠᵸ"},
/*176,20*/ {"Technical","⌀⌌⌜⌢⌬⎍⎴⏐⏢⑀"},
/*36,7*/ {"Weather and Astrological","☀☔☽⚳"},
/*165,9*/ {"Yijing / Tai Xuan Jing","⚊☰䷀𝌀"},
/*10,5*/ {"Historic - Aegean Numbers","𐄂𐄷"},
/*12,3*/ {"Historic - Ancient Symbols","𐆐"},
/*246,3*/ {"Historic - Musical","𝀀"},
/*45,3*/ {"Historic - Phaistos Disc","𐇐"},
/*1,1*/ {"Historic - Subscript","ⱼ"},
/*2,2*/ {"Historic - Superscript","ⱽꝰ"},
/*1,1*/ {"Historic - Supplemental Punctuation","ⸯ"},
/*15,3*/ {"Compatibility - CJK","〶㆒"},
/*1143,133*/ {"Compatibility - Compatibility","℀℅℉ℕℙ℠ℤℨℬℯℳ℻ⅅ㈪㊊㋀㍘㍻㏠𝅗𝅥𝆹𝅥𝐀𝑖𝒞𝒢𝒥𝒩𝒮𝒻𝒽𝓅𝔇𝔍𝔖𝔞𝔻𝕀𝕆𝕊𝕒𝚨𝛂𝛜𝛼𝜖𝜶𝝐𝝰𝞊𝞪𝟄￤￨￭"},
/*8,8*/ {"Compatibility - Currency","₨﷼﹩＄￠￥"},
/*204,19*/ {"Compatibility - Latin","¨ª¯²¸ᵢ⒜㉐㋌㍱㎀㏿"},
/*42,45*/ {"Compatibility - Math","⁺₊⅀∬∯⨌⩴⫝̸𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃﬩﹢﹤＋＜｜～￢￩"},
/*15,2*/ {"Compatibility - Subscript","₀"},
/*16,6*/ {"Compatibility - Superscript","⁰⁴℠™"},
},
{{"Punctuation"},
/*18,18*/ {"ASCII",",;:!¡?¿.·'\"@*/\\&#%"},
/*4,3*/ {"CJK","、〽"},
/*4,4*/ {"Connector","_‿⁔⁀"},
/*13,11*/ {"Dash","-֊᠆‐‒〜〰゠⸚־"},
/*148,129*/ {"Other","᭠᠇⁓・՝،٫߸᠂᠈꘍﹅؛⁏։؞፡፣᠄៖᭝՜߹᥄՞؟፧᥅꘏‽⸘᠁۔።᠃᠉᙮᭜꘎।꣎᰻꤯၊។᭞꩝᱾߷፨᭚⁕⸙⁋⁎⁑٭⁊٪‰؉‱؊†‧⁃⁌′‵‸※⁐⁁⸛⸞՚՟׀׃׳᠀᠊॰෴๚༄࿐་།྅࿒᰽၌៘᙭꤮꩜๏‖᧞"},
/*113,44*/ {"Paired","‘‹“〝«»([]{}༺⁅⧼⦃⟬⸜⸠〈〔﴾❨⟅⟦⧘"},
/*1,1*/ {"Historic - Dash","⸗"},
/*84,49*/ {"Historic - Other","׆܀჻᛫᜵᨞⁖⁘⳹⳾⸀⸆⸋⸎⸪⸰꙳꙾꡴꥟𐄀𐎟𐏐𐤟𐤿𐩐𒑰"},
/*10,8*/ {"Historic - Paired","᚛⸂⸉⸌"},
/*15,13*/ {"Compatibility - ASCII","！％＊，．：？＼"},
/*2,2*/ {"Compatibility - CJK","｡､"},
/*6,5*/ {"Compatibility - Connector","︳﹍＿"},
/*6,6*/ {"Compatibility - Dash","‑︱﹘﹣－"},
/*44,31*/ {"Compatibility - Other",";·༌‗․″‶‼‾⁇⁗︐︙︰﹉﹐﹔﹟﹨﹪･"},
/*40,22*/ {"Compatibility - Paired","⁽₍︗︵﹇﹙（［］｛｝｟｢"},
},
{{"Number"},
/*290,58*/ {"Decimal","0٠۰߀०০੦૦୦௦౦೦൦๐໐༠၀႐០᠐᥆᧐᭐᱀᱐꘠꣐꤀꩐"},
/*131,113*/ {"Other","৸௰൰፲𝍩⓿౸༳៰⓵❶➀➊፩৴౹౼༪៱𝍠⓾❿➉➓⓫⓶❷➁➋፪৵౺౽༫៲𝍡⓴⓷❸➂➌፫৶౻౾༬៳𝍢⓸❹➃➍፬৷༭៴𝍣⓹❺➄➎፭༮៵𝍤⓺❻➅➏፮༯៶𝍥⓻❼➆➐፯༰៷𝍦⓼❽➇➑፰༱៸𝍧⓽❾➈➒፱༲៹𝍨"},
/*20,5*/ {"Historic - Decimal","᮰𐒠"},
/*182,24*/ {"Historic - Letter","ᛮↀↅ〇〡〸𐅀𐍁𐍊𐏑𒐀"},
/*67,18*/ {"Historic - Other","⳽𐄇𐅵𐆊𐌠𐤖𐩀"},
/*60,5*/ {"Compatibility - Decimal","𝟎０"},
/*32,2*/ {"Compatibility - Letter","Ⅰ"},
/*151,25*/ {"Compatibility - Other","²¹¼⁰⁴₀⅓①⓪㆒㈠㉑㊀㊱"},
},
{{"Invisibles"},
/*34,17*/ {"Format","­؀឴​‪⁠𝅳﻿￹"},
/*260,8*/ {"Other","͏᠋󠄀︀"},
/*4,4*/ {"Whitespace"," ᠎ "},
/*2,2*/ {"Historic - Format","۝܏"},
/*3,3*/ {"Historic - Other","ᅟㅤ"},
/*1,1*/ {"Historic - Whitespace"," "},
/*1,1*/ {"Compatibility - Other","ﾠ"},
/*15,6*/ {"Compatibility - Whitespace","    　"},
},
{{"Modifier"},
/*7,4*/ {"Enclosing","⃝⃢"},
/*181,72*/ {"Nonspacing","𝅧𝅻𝆅𝆪︡︣̲̓̸̧́̀̆̂̌̊͂̈̋̃̇̄̉̍̕̩̳̹ͅ͐︢︠᷄͢͡᷋ًٰ॑〪゙⃐⃥⃡᷊"},
/*125,72*/ {"Spacing","ـʹˆˬꜗːᶛᶢʻʽᶦᶤᶧᶥᶨᶡᶫᶪᶩᶬᶰᶮᶱᶸᶶᶣᶭᶷᶹˀʼˮʾˁᵝᶿᵠჼⵯ𝅥𝅭`^͵˂˒˞˥˭꜈꞉"},
/*45,10*/ {"Historic - Nonspacing","ͣ᷀᷎᷾𐇽"},
/*27,6*/ {"Historic - Spacing","˯꜀꜠"},
/*4,4*/ {"Compatibility - Nonspacing","̀̓"},
/*33,22*/ {"Compatibility - Spacing","˘΄ᵦ᾽᾿῍῝῭´゛＾｀￣"},
},
{{"Latin"},
/*326,326*/ {"Common","aAáÁàÀăĂắẮằẰẵẴẳẲâÂấẤầẦẫẪẩẨåÅäÄãÃąĄāĀảẢạẠặẶậẬæÆbBɓƁcCćĆčČċĊçÇdDďĎđĐðÐɗƊeEéÉèÈêÊếẾềỀễỄểỂěĚëËẽẼėĖęĘēĒẻẺẹẸệỆəƏfFgGğĞġĠģĢhHħĦiIíÍìÌîÎïÏĩĨİįĮīĪỉỈịỊıjJkKķĶƙƘlLĺĹľĽļĻłŁmMnNńŃňŇñÑņŅoOóÓòÒôÔốỐồỒỗỖổỔöÖőŐõÕøØōŌỏỎơƠớỚờỜỡỠởỞợỢọỌộỘœŒpPqQrRŕŔřŘsSśŚšŠşŞșȘßẞtTťŤțȚuUúÚùÙûÛůŮüÜűŰũŨųŲūŪủỦưƯứỨừỪữỮửỬựỰụỤvVwWẃẂẁẀŵŴẅẄxXyYýÝỳỲŷŶÿŸỹỸỷỶỵỴzZźŹžŽżŻþÞʻʿ̇"},
/*662,621*/ {"Other","ǎǍǻǺǟǞȧȦǡǠȁȀȃȂḁḀǽǼǣǢᴀⱥȺᶏᴁⱯⱭᶐḃḂḅḄḇḆƀɃᴃᵬᶀƃƂĉĈḉḈᴄȼȻƈƇḋḊḑḐḍḌḓḒḏḎꝺꝹȸᴅᵭᶁƉᶑƌƋȡĕĔȩȨḝḜḗḖḕḔȅȄȇȆḙḘḛḚᴇɇɆᶒǝƎᶕƐᶓᴈḟḞꝼꝻᵮᶂƒƑⅎℲǵǴĝĜǧǦḡḠᵹꝽǥǤᶃƓᵷꝿꝾƔƣƢĥĤȟȞḧḦḣḢḩḨḥḤḫḪẖƕǶⱨⱧⱶⱵꜧꜦĭĬǐǏḯḮȉȈȋȊḭḬᴉƗᵻᶖƖᵼĵĴǰȷᴊɉɈḱḰǩǨḳḲḵḴᴋᶄⱪⱩḷḶḹḸḽḼḻḺᴌƚȽⱡⱠⱢᶅȴꞁꞀƛḿḾṁṀṃṂᴍᵯᶆⱮǹǸṅṄṇṆṋṊṉṈᴎᵰƝȠᶇȵŊŏŎǒǑȫȪṍṌṏṎȭȬȯȮȱȰǿǾǫǪǭǬṓṒṑṐȍȌȏȎᴏᴑᴔᴓƆᴐᴒᶗᴖƟȣȢᴕṕṔṗṖᴘᵽⱣᵱᶈƥƤȹɋɊĸṙṘŗŖȑȐȓȒṛṚṝṜṟṞꞃꞂƦᴙɍɌᵲᴚᶉⱤᵳṥṤŝŜṧṦṡṠṣṢṩṨꞅꞄᵴᶊȿƩᶋᶘẗṫṪţŢṭṬṱṰṯṮꞇꞆᵺꜩꜨᴛŧŦⱦȾᵵƭƬƮȶŭŬǔǓǘǗǜǛǚǙǖǕṹṸṻṺȕȔȗȖṳṲṷṶṵṴᴜᵫɄᵾᶙƜᴟƱᵿṽṼṿṾᴠᶌƲⱱⱴɅẘẇẆẉẈᴡⱳⱲẍẌẋẊᶍẙẏẎȳȲɏɎƴƳẑẐẓẒẕẔᴢƶƵᵶᶎȥȤɀⱬⱫƷǯǮᴣᶚꜫꜪꜭꜬꜯꜮɂɁꜣꜢꞌꞋᴤꜥꜤᴦʹˆˉˍˬꜗꞈᵃₐᴬᵆᵄᶛᵇᴮᶜᵈᴰᶞᵉₑᴱᵊₔᵋᶟᵌᶠᵍᴳᶢᴴʽᴵᶦᵎᶤᶧᶥᴶᶨᶡᵏᴷˡᴸᶫᶪᶩᵐᴹᶬᴺᶰᴻᶮᵑₒᴼᵓᶱᴽᵖᴾᶲʳᴿʵˢᶳᵗᵀᶵᵘᵁᶸᵙᶶᶣᵚᶭᶷᵛᶹᵂˣₓʸᶻˀˮʾˁᵜᶿᵠᵸ`^˂˒˟˥˭꜈꞉℄℈℔℗℞℣℥℧℮℺⅊⅌"},
/*183,146*/ {"Phonetics (IPA)","aæɐbʙɓcçɕdðʤɖeəɛɘɚɜɤfɡɠʛɣhħʜɦiɪɨjʝɟʄkʟɫʎmɱnɴɲŋoøœɶɔɵpɸqʀɹɽʁsʂtʧʈuʉɥɯʊvʋwʍxʏzʐʔʡǀʘβθχˈˌːˠʰʴʷʼˤ̲̓̧́̀̆̊̈̋̃̄̏̕̩̳̹͜͡˞→↑↓↗"},
/*24,24*/ {"Phonetics (X-IPA)","ʣʥʚʩɩʞʪɷʠɼɿʅʨʦʇʮʓʖʬ"},
/*149,32*/ {"Historic - Other","ƄƍƧƪƸǷȜ˯჻ẜẟỺↀⱷ꜀꜠ꜰꟻ"},
/*148,44*/ {"Compatibility - Other","¨ª¯´¸ºĲĿſǄǱ˘ᵢẚⁱⁿ℀℃℅℉№℠Kℹ℻ⅠﬀＡａ"},
},
{{"Other European Scripts"},
/*84,84*/ {"Armenian","աԱբԲգԳդԴեԵզԶէԷըԸթԹժԺիԻլԼխԽծԾկԿհՀձՁղՂճՃմՄյՅնՆշՇոՈչՉպՊջՋռՌսՍվՎտՏրՐցՑւՒփՓքՔօՕֆՖՙ֊՝՜՞՚՟"},
/*256,2*/ {"Braille","⠀"},
/*290,290*/ {"Cyrillic","аАӑӐӓӒәӘӛӚӕӔбБвВгГґҐғҒӻӺҕҔӷӶдДԁԀђЂԃԂѓЃҙҘеЕѐЀёЁӗӖєЄжЖӂӁӝӜҗҖзЗԅԄԑԐӟӞѕЅӡӠԇԆиИѝЍӣӢҋҊӥӤіІїЇйЙјЈкКқҚӄӃҡҠҟҞҝҜԟԞԛԚлЛᴫӆӅԓԒԡԠљЉԉԈԕԔмМӎӍнНӊӉңҢӈӇԣԢҥҤњЊԋԊоОӧӦөӨӫӪпПҧҦҁҀрРҏҎԗԖсСԍԌҫҪтТԏԎҭҬћЋќЌуУӯӮўЎӱӰӳӲүҮұҰѹѸфФхХӽӼӿӾҳҲһҺѡѠѿѾѽѼѻѺцЦҵҴчЧӵӴҷҶӌӋҹҸҽҼҿҾџЏшШщЩъЪыЫӹӸьЬҍҌѣѢэЭӭӬюЮяЯԙԘѥѤѧѦѫѪѩѨѭѬѯѮѱѰѳѲѵѴѷѶҩҨԝԜӏӀᵸ҈҇҂"},
/*38,5*/ {"Georgian","აჷჼ"},
/*286,285*/ {"Greek","αΑἀἈἄἌᾄᾌἂἊᾂᾊἆἎᾆᾎᾀᾈἁἉἅἍᾅᾍἃἋᾃᾋἇἏᾇᾏᾁᾉάΆᾴὰᾺᾲᾰᾸᾶᾱᾹᾳᾼβΒγΓᴦδΔεΕἐἘἔἜἒἚἑἙἕἝἓἛέΈὲῈζΖηΗἠἨἤἬᾔᾜἢἪᾒᾚἦἮᾖᾞᾐᾘἡἩἥἭᾕᾝἣἫᾓᾛἧἯᾗᾟᾑᾙήΉῄὴῊῂῆῃῌθΘιΙἰἸἴἼἲἺἶἾἱἹἵἽἳἻἷἿίΊὶῚῐῘῖϊΪΐῒῗῑῙϳκΚλΛᴧμΜνΝξΞοΟὀὈὄὌὂὊὁὉὅὍὃὋόΌὸῸπΠᴨρΡῤῬᴩϼσΣςτΤυΥὐὔὒὖὑὙὕὝὓὛὗὟύΎὺῪῠῨῦϋΫΰῢῧῡῩφΦχΧψΨᴪωΩὠὨὤὬᾤᾬὢὪᾢᾪὦὮᾦᾮᾠᾨὡὩὥὭᾥᾭὣὫᾣᾫὧὯᾧᾯᾡᾩώΏῴὼῺῲῶῳῼᵝᶿͺᵠ͵϶"},
/*128,6*/ {"Historic - Coptic","ϢⲀ⳹"},
/*55,15*/ {"Historic - Cypriot","𐠀𐠈𐠊𐠷𐠼𐠿"},
/*114,10*/ {"Historic - Cyrillic","҃ⷠꙀꙢ꙼"},
/*82,6*/ {"Historic - Georgian","Ⴀჱⴀ"},
/*94,4*/ {"Historic - Glagolitic","Ⰰⰰ"},
/*27,3*/ {"Historic - Gothic","𐌰"},
/*180,22*/ {"Historic - Greek","ͰͶͻϏϕϲϴϷϽ𐅀𝈀"},
/*211,21*/ {"Historic - Linear B","𐀀𐀍𐀨𐀼𐀿𐁐𐂀"},
/*29,2*/ {"Historic - Ogham"," "},
/*35,6*/ {"Historic - Old Italic","𐌀𐌠"},
/*78,4*/ {"Historic - Runic","ᚠᛮ"},
/*48,3*/ {"Historic - Shavian","𐑐"},
/*6,3*/ {"Compatibility - Armenian","ևﬓ"},
/*45,35*/ {"Compatibility - Greek","΄ϒϰϵᵦάέήίόύώΆ᾽ΈΉ῍ΐΊ῝ΰΎ῭ΌΏ´Ω"},
},
{{"American Scripts"},
/*630,18*/ {"Canadian Aboriginal","ᐁᕽᙯᕾᙰᖎᙱᖖᕼᖧ᙮᙭"},
/*85,2*/ {"Cherokee","Ꭰ"},
/*80,3*/ {"Historic - Deseret","𐐀"},
},
{{"African Scripts"},
/*461,130*/ {"Ethiopic","ሀⶀሐᎀⶁሠⶂሰⶃሸⶄቀቊቐቘቚበᎄⶅቨⶆቸⶇኀኊነⶈኘⶉአⶊከኲኸዀዂወዘⶋዠⶌዸⶍጀⶎገጒጘⶓጠⶏጨⶐጰⶑጸᎈፐᎌⶒፘⶠⶨⶰⶸⷀⷈⷐⷘ፟፡፣።፠፨᎐፲፩"},
/*56,13*/ {"Nko","ߊߺߴ߫߸߷߶߀"},
/*55,3*/ {"Tifinagh","ⴰⵯ"},
/*300,56*/ {"Vai","ꔀꘓꔍꘔꔟꘕꔴꘖꕈꘗꕓꘐꘘꕙꘙꕛꘚꕡꘑꕫꘪꕯꘛꖆꘒꖈꘜꖵꘝꗌꘫꘞꗒꘟꗙ꘏꘎꘠"},
/*3,2*/ {"Historic - Nko","ߨ"},
/*40,6*/ {"Historic - Osmanya","𐒀𐒠"},
},
{{"Middle Eastern Scripts"},
/*226,159*/ {"Arabic","ﹳءٴآٲٱؤٳݳئٻپڀݐةٹټٿجڃچڿڇحځڅݗݮݲݼدڈڏۮݙرڑۯݛݫݱسښۺݜݭݰݽصڝۻطڟعڠۼݝفڡݠقڧكکݢلڵݪمݥنںڹݧهھہۿەۀوۄۏݸىیېݵےݺؐٖ؍٫؞۔٭٪؉؈؎﷽؆۰؋۽"},
/*53,35*/ {"Hebrew","אװזײכךלמםנןספףצץקְֽּֿׁׂﬞ־׀׃׳"},
/*50,31*/ {"Thaana","ހޙށޜބޢވޥމޛތޘޠލޤޏޝޑޱަ"},
/*39,13*/ {"Historic - Arabic","ؕػٮڎۖ۞ݾ"},
/*49,3*/ {"Historic - Carian","𐊠"},
/*982,9*/ {"Historic - Cuneiform","𒀀𒐀𒑰"},
/*45,7*/ {"Historic - Hebrew","֑ׄﬠﭏ"},
/*29,3*/ {"Historic - Lycian","𐊀"},
/*27,5*/ {"Historic - Lydian","𐤠𐤿"},
/*50,6*/ {"Historic - Old Persian","𐎠𐏈"},
/*27,5*/ {"Historic - Phoenician","𐤀𐤟"},
/*77,6*/ {"Historic - Syriac","܀܏ݍ"},
/*31,5*/ {"Historic - Ugaritic","𐎀𐎟"},
/*735,17*/ {"Compatibility - Arabic","ٵﭐﯓﵐﶒﷰﹰﹴﹶ"},
/*35,13*/ {"Compatibility - Hebrew","יִײַ﬩טּמּנּףּצּ"},
},
{{"South Asian Scripts"},
/*88,39*/ {"Bengali","অৠঌৡএওৎথপৰলৱশঽ়ঁ৺০৸৲াৢেোৗ"},
/*99,37*/ {"Devanagari","ॐॲऄॠऌॡऍॻघॼझॾढॿभऽॽॱ़ँ॓०ाॢॅ"},
/*83,33*/ {"Gujarati","ૐઅૠઌૡઍએઓપલવઽ઼ઁ૦૱ાૢૅેો"},
/*73,37*/ {"Gurmukhi","ੴੳਉਓਅਐਔੲਇਏਸਕਪਲਵੜ਼ਁੰ੦ੑੵਾੇੋ"},
/*85,32*/ {"Kannada","ಅೠಌೡಎಒಪವಳಽ಼ಂೱ೦ಾೢೆೊೕ"},
/*74,14*/ {"Lepcha","ᰀᱍᰊ᰷᰻ᰤᰶᰦ"},
/*66,13*/ {"Limbu","ᤀ᤹᥄᥀᥆ᤠᤰ"},
/*95,42*/ {"Malayalam","അൠഌൡഎഒൿകൺണൻനപർറൽലൾളഽം൹൦ാൢെൊൗ്"},
/*48,4*/ {"Ol Chiki","ᱚ᱐"},
/*82,36*/ {"Oriya","ଅୠଌୡଏଓପୟରଲଵୱଶଽ଼ଁ୰୦ାୢେୋୖ"},
/*81,8*/ {"Saurashtra","ꢂꢀ꣎ꢴ"},
/*80,20*/ {"Sinhala","අකඳලවං෴්ාූෘෲ"},
/*72,33*/ {"Tamil","ௐஃஅஎஒஙஜஞணநமஂ௳௺௦௹ாெொௗ"},
/*93,42*/ {"Telugu","అౠఌౡఎఒౘఛౙఝపవఽఁ౿౦౸౼౺౽౻౾ాౢెొౕ"},
/*181,99*/ {"Tibetan","ཀཫཁངཉཎནམཝཪཬལༀྈ༘༵༷ྂ྆༹࿆ཾ༔༺༄࿐་།྅࿒༁༓༕༚༴༶༸༾྾࿇࿎༠༳༪ྐྔྙྞྣྨྭྺྮྻྲྼླཱྀེུ྄"},
/*1,1*/ {"Historic - Kannada","ೞ"},
/*65,24*/ {"Historic - Kharoshthi","𐨀𐨅𐨌𐨕𐨙𐨸𐨿𐩐"},
/*56,2*/ {"Historic - Phags Pa","ꡀ"},
/*44,2*/ {"Historic - Syloti Nagri","ꠀ"},
/*3,3*/ {"Compatibility - Bengali","ড়য়"},
/*8,2*/ {"Compatibility - Devanagari","क़"},
/*6,5*/ {"Compatibility - Gurmukhi","ਲ਼ਸ਼ਖ਼ਫ਼"},
/*2,2*/ {"Compatibility - Oriya","ଡ଼"},
/*18,18*/ {"Compatibility - Tibetan","༌གྷཌྷདྷབྷཛྷཀྵཱཱིུླཱྀྀྒྷྜྷྡྷྦྷྫྷྐྵ"},
},
{{"Southeast Asian Scripts"},
/*121,38*/ {"Balinese","ᬅᭅᬔᭇᬣᭈᬨᭉᬰᭊᬳ᭫᬴ᬀ᭠᭝᭜᭞᭚᭡᭴᭐ᬵ"},
/*83,18*/ {"Cham","ꨀꩀꩄ꩝꩜꩐ꨳꨩꩃꩌ"},
/*48,10*/ {"Kayah Li","ꤊ꤫꤯꤮꤀ꤦ"},
/*141,26*/ {"Khmer","កៜឥឩៗំ៓៖។៘᧠០៛៰឴្"},
/*62,33*/ {"Lao","ກຄງຊຍດນມລວສອາຽເໆ່໐ັິົ"},
/*156,129*/ {"Myanmar","ကၵခၶဂၷဃၚစၸဆၹဈၛၡဉၺညၮတၻဓၼပၽႎဗၿဘႀၐၥသဿဟႁဠၜၯၦအၒဧံႍ၊႞၀႐၁႑၂႒၃႓၄႔၅႕၆႖၇႗၈႘၉႙ၞျၠွႂှာါႃၲိၱီဳုၳူၖေႄဵႅဲဴၢၧႆ္ၣၩႇႋႈႌႉႏ"},
/*80,12*/ {"New Tai Lue","ᦀᧁ᧐᧞ᦰᧈ"},
/*35,4*/ {"Tai Le","ᥐᥰ"},
/*85,15*/ {"Thai","กาเ๎็๚๏ัิ"},
/*30,4*/ {"Historic - Buginese","ᨀ᨞"},
/*20,2*/ {"Historic - Buhid","ᝀ"},
/*21,2*/ {"Historic - Hanunoo","ᜠ"},
/*3,3*/ {"Historic - Khmer","ឨ៑៝"},
/*37,3*/ {"Historic - Rejang","ꤰ꥟"},
/*55,4*/ {"Historic - Sundanese","ᮀᮮ"},
/*20,4*/ {"Historic - Tagalog","ᜀᜎ"},
/*18,6*/ {"Historic - Tagbanwa","ᝠᝮᝲ"},
/*3,3*/ {"Compatibility - Lao","ຳໜ"},
/*1,1*/ {"Compatibility - Thai","ำ"},
},
{{"Hangul"},
/*1176,2*/ {"ᄀ HANGUL CHOSEONG KIYEOK","가"},
/*588,2*/ {"ᄂ HANGUL CHOSEONG NIEUN","나"},
/*1176,2*/ {"ᄃ HANGUL CHOSEONG TIKEUT","다"},
/*588,2*/ {"ᄅ HANGUL CHOSEONG RIEUL","라"},
/*588,2*/ {"ᄆ HANGUL CHOSEONG MIEUM","마"},
/*1176,2*/ {"ᄇ HANGUL CHOSEONG PIEUP","바"},
/*1176,2*/ {"ᄉ HANGUL CHOSEONG SIOS","사"},
/*588,2*/ {"ᄋ HANGUL CHOSEONG IEUNG","아"},
/*1176,2*/ {"ᄌ HANGUL CHOSEONG CIEUC","자"},
/*588,2*/ {"ᄎ HANGUL CHOSEONG CHIEUCH","차"},
/*588,2*/ {"ᄏ HANGUL CHOSEONG KHIEUKH","카"},
/*588,2*/ {"ᄐ HANGUL CHOSEONG THIEUTH","타"},
/*588,2*/ {"ᄑ HANGUL CHOSEONG PHIEUPH","파"},
/*588,2*/ {"ᄒ HANGUL CHOSEONG HIEUH","하"},
/*334,8*/ {"Historic - Archaic Hangul","ᄀᅟᆨㄱ"},
/*83,11*/ {"Compatibility - Compatibility","㈀㉠ﾡﾤﾧﾰ"},
/*31,14*/ {"Compatibility - ᅡ Vowel/Trailing/Filler","ﾠﾣﾥﾪￂￊￒￚ"},
},
{{"Other East Asian Scripts"},
/*65,58*/ {"Bopomofo","ㄅㆠㄆㆴㄇㄪㄉㆵㄋㆣㄎㆶㄫㆭㄏㆷㄐㆢㄑㄬㄓㆡㄘㆩㄛㆧㆦㄜㆤㄞㆮㄟㆯㄡㆲㄥㆰㆬㄦㆪㆳㄨㆫㆨㄩㄭ"},
/*88,13*/ {"Hiragana","ぁゔぇゕかゖけゝ"},
/*112,69*/ {"Katakana","ァヴェヵカㇰクヶケㇱシㇲスㇳトㇴヌㇵハㇶヒㇷフㇸヘㇹホㇺムㇻラㇼリㇽルㇾレㇿロヷヰヸヱヹヲヺンﾞーｰヽ"},
/*153,133*/ {"Mongolian","ᢀᠠᢇᠡᡄᡝᠢᡅᡞᡳᢈᡟᠣᡆᠤᡇᡡᠥᡈᠦᡉᡠᠧᡊᡢᢊᢛᠪᡋᠫᡌᡦᠬᡍᠭᡎᡤᢚᡥᠮᡏᠯᡧᢜᢢᢤᠲᡐᡨᠳᡑᡩᠴᡒᡱᡜᢋᠵᡓᡪᡷᠶᡕᡲᠷᡵᠸᡖᠹᡫᡶᠺᡗᡣᡴᢉᠻᡔᡮᠽᡯᡘᡬᠾᡙᡭᠿᡚᡰᢌᢞᢍᢟᢏᢘᢠᢑᢡᢒᢨᢔᢣᢕᢙᢖᢦᢪᡃ᠋᠆᠄᠁᠉᠀᠊᠐ᢩ"},
/*1220,7*/ {"Yi","ꀀꀖꀕ꒐"},
/*1,1*/ {"Compatibility - Hiragana","ゟ"},
/*191,9*/ {"Compatibility - Katakana","ヿ㋐㌀ｦｱ"},
},
{{"Han 1-Stroke Radicals"},
/*43,5*/ {"一","一丽亐卄"},
/*13,4*/ {"丨","丨中"},
/*9,4*/ {"丶","丶举义"},
/*26,5*/ {"丿","丿乊尹"},
/*43,5*/ {"乙","乙乣龴"},
/*7,2*/ {"亅","亅"},
/*320,81*/ {"Less common - Other","㐀𠀀𠀜𠀞𠀦𠀰𠀸𠀺𠀽𠁊𠁝𠁟𠁥𠁳𠁸𠂩𠂭𠂯𠂲𠂶𠃬𠃲𠤢𠧝𢆡𤱡𤳏𥝀丽串亂丹不了並"},
},
{{"Han 2-Stroke Radicals"},
/*19,4*/ {"二","二云"},
/*26,2*/ {"亠","亠"},
/*645,2*/ {"人","人"},
/*38,2*/ {"儿","儿"},
/*7,3*/ {"入","入氽"},
/*24,3*/ {"八","八龹"},
/*21,3*/ {"冂","冂最"},
/*21,2*/ {"冖","冖"},
/*53,2*/ {"冫","冫"},
/*21,2*/ {"几","几"},
/*11,2*/ {"凵","凵"},
/*159,9*/ {"刀","㓤刀𠜎𠜱𠝹"},
/*93,4*/ {"力","力勘"},
/*28,2*/ {"勹","勹"},
/*5,2*/ {"匕","匕"},
/*31,3*/ {"匚","匚龨"},
/*9,2*/ {"匸","匸"},
/*27,5*/ {"十","十卅龺"},
/*13,2*/ {"卜","卜"},
/*25,2*/ {"卩","卩"},
/*53,3*/ {"厂","厂虒"},
/*18,2*/ {"厶","厶"},
/*28,3*/ {"又","又壡"},
/*152,3*/ {"讠","䜣讠"},
/*3066,247*/ {"Less common - Other","㐩㓥㔯㘞䜤𠀝𠀥𠁉𠁜𠂬𠂮𠂰𠄞𠄵𠅘𠅲𠅺𠅾𠆋𠆔𠆖𠆚𠆝𠆳𠈃𠈥𠋒𠌠𠌫𠍣𠎙𠎝𠎷𠏔𠏨𠐝𠑃𠑲𠑵𠓍𠔈𠔙𠔼𠕬𠖠𠙘𠙛𠙭𠙽𠚒𠚜𠜏𠜲𠝺𠞝𠠌𠤣𠤬𠧞𠧹𠨄𠪺𠫉𠭷𡥋𡪞𢇕𢍭𣥥𥂳𦎅𧮪𠄢凵切冒𠔥劳㒻𠠄𠣞卵來勒凜北便參亮勵力列令例僚劉六倫利匿什刺兀﨎凞侮况"},
},
{{"Han 3-Stroke Radicals"},
/*790,67*/ {"口","㕷㖡㖭㖿㗎㗳㗾口啠噖𠱓𠱸𠲖𠳏𠳕𠴕𠵼𠵿𠸎𠹷𠺝𠺢𠻗𠻹𠼭𠽌𠾴𠾼𠿪𡁜𡁯𡁵𡁻𡃁𡃉"},
/*74,5*/ {"囗","囗龱𡇙"},
/*461,9*/ {"土","土墩壢龳龶龼"},
/*24,3*/ {"士","垂士"},
/*7,2*/ {"夂","夂"},
/*12,2*/ {"夊","変"},
/*18,2*/ {"夕","夕"},
/*76,2*/ {"大","大"},
/*476,4*/ {"女","女娅"},
/*48,2*/ {"子","子"},
/*121,3*/ {"宀","宀牢"},
/*23,2*/ {"寸","寸"},
/*20,3*/ {"小","小龸"},
/*22,2*/ {"尢","尢"},
/*53,3*/ {"尸","尸尺"},
/*3,2*/ {"屮","屮"},
/*363,3*/ {"山","乢山"},
/*9,4*/ {"巛","巛巢"},
/*12,2*/ {"工","工"},
/*13,2*/ {"己","己"},
/*116,6*/ {"巾","巾幑𢃇"},
/*8,2*/ {"干","干"},
/*6,3*/ {"幺","乡幺"},
/*118,3*/ {"广","广龐"},
/*10,2*/ {"廴","廴"},
/*13,2*/ {"廾","廾"},
/*8,2*/ {"弋","弋"},
/*61,2*/ {"弓","弓"},
/*17,2*/ {"彐","彐"},
/*17,4*/ {"彡","彡彫"},
/*80,2*/ {"彳","彳"},
/*151,2*/ {"纟","纟"},
/*52,2*/ {"门","门"},
/*1,1*/ {"飞","飞"},
/*51,2*/ {"饣","饣"},
/*60,2*/ {"马","马"},
/*7852,389*/ {"Less common - Other","㕣㕸㖢㖮㗀㗏㗴㗿㘟䌶䦶䧹䭪䯃𠀛𠀯𠀷𠀹𠀼𠁤𠁷𠃱𠄴𠅗𠅱𠅹𠅽𠆊𠆓𠆕𠆙𠆲𠈂𠈤𠌞𠏓𠏧𠓌𠔘𠙗𠙚𠙼𠚛𠨃𠭶𠮙𠱔𠱹𠲗𠳐𠳖𠳬𠴖𠴧𠵽𠶀𠸐𠹸𠺞𠺣𠻘𠻻𠼯𠽍𠾨𠾵𠾽𠿫𡁝𡁰𡁷𡁼𡃂𡃊𡄊𡅗𡇎𡇚𡋝𡑻𡒢𡓜𡓸𡔸𡕇𡕏𡗝𡢐𡣣𡥌𡪟𡯦𡶥𢃈𢇖𢉗𢋝𢌈𢍮𢐬𢑗𢔭𢖆𢖌𢖜𢖢𢨐𢻈𣉡𣊒𣑧𣡳𣥲𣦏𣦭𣼙𤀢𤏠𤔗𤯏𤯽𦈈𦊤𦋪𦥈𧮥𧯧𨗓𨷿𨹴𩟾𩧦𪌛叫壮廾弢形𡴋𢆟媵嶲句契喇嵐廊壟壘寧復塞呂年咽廉囹寮崙律吏吝度宅廓嗀﨏喝喝"},
},
{{"Han 4-Stroke Radicals"},
/*583,5*/ {"心","㥠心𢞵"},
/*46,2*/ {"戈","戈"},
/*21,2*/ {"戶","戶"},
/*757,29*/ {"手","㧟㧸㧾㨘㩒㩧手龵𢫕𢭃𢯊𢱑𢱕𢳂𢴈𢵌𢵧𢺳"},
/*5,2*/ {"支","支"},
/*85,4*/ {"攴","啟攴贁"},
/*17,3*/ {"文","文齐"},
/*13,2*/ {"斗","斗"},
/*21,2*/ {"斤","斤"},
/*39,2*/ {"方","方"},
/*5,2*/ {"无","无"},
/*271,6*/ {"日","勗日曽耆龧"},
/*23,7*/ {"曰","勗曰曾朁"},
/*33,3*/ {"月","月膤"},
/*1018,4*/ {"木","㭎木渠"},
/*66,2*/ {"欠","欠"},
/*24,3*/ {"止","止龰"},
/*58,2*/ {"歹","歹"},
/*24,2*/ {"殳","殳"},
/*9,2*/ {"毋","毋"},
/*7,2*/ {"比","比"},
/*52,2*/ {"毛","毛"},
/*5,2*/ {"氏","氏"},
/*32,2*/ {"气","气"},
/*1079,6*/ {"水","水泶𣲷"},
/*454,10*/ {"火","㷧㷫火蒸黙龦龽𤓓"},
/*13,3*/ {"爪","噕爪"},
/*5,2*/ {"父","父"},
/*4,2*/ {"爻","爻"},
/*9,3*/ {"爿","丬爿"},
/*18,2*/ {"片","片"},
/*2,2*/ {"牙","牙"},
/*81,2*/ {"牛","牛"},
/*217,3*/ {"犬","㹴犬"},
/*16,4*/ {"见","见觇"},
/*71,2*/ {"贝","贝"},
/*53,2*/ {"车","车"},
/*7,2*/ {"韦","韦"},
/*13,2*/ {"风","风"},
/*10736,330*/ {"Less common - Other","㚇㣺㥡㧠㧹㧿㨙㩓㩨㬺㭏㷨㷬㹵䞌䢀𠁞𠂱𠆛𠎛𠎶𠑂𠑱𠕫𠫈𡄉𡗜𢌇𢖩𢞶𢨑𢫖𢭄𢯋𢱀𢱒𢱖𢳃𢴉𢵍𢵨𢺴𢻉𢾦𢿇𣂬𣉢𣊓𣌛𣌟𣍩𣍱𣑨𣜣𣞐𣡴𣣭𣥦𣥳𣦌𣦐𣦮𣪮𣲸𣼚𤀣𤋴𤎁𤎃𤏡𤑄𤓐𤓔𤓠𤔘𤕂𥇴𥤔𥫂𦑑𦜳𦡖𦦨𦴶𦻇𧹑𨐅𨐳𩏼𩖰𩙥𩠮𩠰灰𣊸忍最朗𣫺煅𣍟𣎓更滑懶樂欄濫拉朗擄牢樓拏怒泌殺沈掠梁旅曆憐烈念獵怜惡料暈杻戮淪慄易溺燐林狀拓洞晴猪悔惘爵𢡊"},
},
{{"Han 5-Stroke Radicals"},
/*5,2*/ {"玄","玄"},
/*340,3*/ {"玉","㻐玉"},
/*10,2*/ {"瓜","瓜"},
/*50,2*/ {"瓦","瓦"},
/*7,2*/ {"甘","甘"},
/*9,2*/ {"生","生"},
/*8,2*/ {"用","用"},
/*89,6*/ {"田","田畡畩"},
/*7,2*/ {"疋","疋"},
/*230,6*/ {"疒","疒𤶸𤷪"},
/*7,2*/ {"癶","癶"},
/*50,3*/ {"白","畠白"},
/*18,3*/ {"皮","皮龾"},
/*47,2*/ {"皿","皿"},
/*241,7*/ {"目","䁥䁪目鿃𥄫"},
/*7,2*/ {"矛","矛"},
/*17,2*/ {"矢","矢"},
/*330,5*/ {"石","䂻䃟泵石"},
/*128,4*/ {"示","示視视"},
/*7,3*/ {"禸","禸萬"},
/*183,3*/ {"禾","䄷禾"},
/*87,2*/ {"穴","穴"},
/*45,5*/ {"立","立竡靖"},
/*242,2*/ {"钅","钅"},
/*1,1*/ {"长","长"},
/*86,2*/ {"鸟","鸟"},
/*3,2*/ {"龙","龙"},
/*5593,192*/ {"Less common - Other","㺨㻑䁦䁫䂼䃠䄸䥺䴓䶭𠂵𠃫𠃰𠅰𠌟𠌪𠍢𠎘𠖟𠞜𠪹𠳫𠴦𠾧𡇍𡕎𡶤𢑖𢘅𢰿𢾥𢿆𣂫𣜢𣞏𣪭𤣥𤫢𤯐𤯾𤱢𤳐𤳜𤶹𤷫𥀿𥂴𥄬𥇵𥌖𥍅𥗷𥝁𥣸𥤕𥧣𥫃𦦔𦪹𧆆𨐴𨰾𪉁王瘐癩珞盧碌磊稜率磻省略礪璉玲禮療琉率理璘立益琢瞧瑱視靖䀘"},
},
{{"Han 6-Stroke Radicals"},
/*378,2*/ {"竹","竹"},
/*135,4*/ {"米","娄畨米"},
/*423,2*/ {"糸","糸"},
/*28,4*/ {"缶","缶𦉘"},
/*57,2*/ {"网","网"},
/*52,3*/ {"羊","着羊"},
/*68,2*/ {"羽","羽"},
/*11,2*/ {"老","老"},
/*6,2*/ {"而","而"},
/*33,2*/ {"耒","耒"},
/*76,2*/ {"耳","耳"},
/*10,2*/ {"聿","聿"},
/*348,8*/ {"肉","㬹幐肉膥𦟌"},
/*7,2*/ {"臣","臣"},
/*9,2*/ {"自","自"},
/*9,2*/ {"至","至"},
/*16,2*/ {"臼","臼"},
/*17,6*/ {"舌","舌𦧲𦧺"},
/*4,2*/ {"舛","舛"},
/*79,2*/ {"舟","舟"},
/*4,2*/ {"艮","艮"},
/*6,2*/ {"色","色"},
/*984,11*/ {"艸","䓪艸萭蒹龩龷龿"},
/*30,5*/ {"虍","彪虍虓"},
/*470,3*/ {"虫","䘆虫"},
/*12,2*/ {"血","血"},
/*23,2*/ {"行","行"},
/*285,4*/ {"衣","初囊衣"},
/*13,2*/ {"襾","襾"},
/*51,2*/ {"页","页"},
/*2,2*/ {"齐","齐"},
/*8806,206*/ {"Less common - Other","㔮䇖䉶䍂䓫䘇䨀𠂨𠑴𠔻𠤫𡅖𡋜𡢏𡯥𢋜𢐫𢔬𢖅𢖋𢖡𣌞𣍨𣍯𤎀𤑃𤓏𤓟𤕁𤫡𥧢𥫗𦈢𦉙𦊥𦋫𦎆𦑒𦜴𦟍𦡘𦥉𦦕𦦩𦧳𦧻𦪺𦴷𦻈𧆇𧈑𧖡𧷅𨦞𩖕舁𦇚肭䈂䏕𦞧舁䑫花羅落蘭藍臘老綠籠累肋綾索葉若糧練蓮裂簾羚蓼紐罹藺臨笠茶糖行精節着節𥳐"},
},
{{"Han 7-Stroke Radicals"},
/*1,1*/ {"卤","鹾"},
/*53,4*/ {"見","見覗"},
/*47,3*/ {"角","角鵤"},
/*419,6*/ {"言","言龻鿁𧨾"},
/*15,2*/ {"谷","谷"},
/*15,2*/ {"豆","豆"},
/*35,2*/ {"豕","豕"},
/*37,2*/ {"豸","豸"},
/*127,4*/ {"貝","貝贂"},
/*12,2*/ {"赤","赤"},
/*68,3*/ {"走","走龪"},
/*251,7*/ {"足","䟴足𨅝𨈇"},
/*31,2*/ {"身","身"},
/*159,6*/ {"車","車龫鿂𨋢"},
/*21,2*/ {"辛","辛"},
/*5,2*/ {"辰","辰"},
/*221,3*/ {"辵","巡辵"},
/*188,6*/ {"邑","䢵䢼䣅䣓邑"},
/*125,2*/ {"酉","酉"},
/*6,2*/ {"釆","釆"},
/*5,2*/ {"里","里"},
/*1,1*/ {"龟","龟"},
/*5130,126*/ {"Less common - Other","㕢䙷䜪䞑䟵䢃䢶䢽䣆䣔𠐜𠔇𠠋𡓛𡕆𡣢𣌚𣣬𤳛𥍄𥣷𧠆𧨿𧮦𧮫𧯨𧷆𧹘𨅞𨈈𨋣𨐋𨐵𨗔𩄮辞𧢮跋軔豈車邏酪郎路論賂讀諾說辰諒轢輦連說醴遼輪里識輻見諸視調𧻓"},
},
{{"Han 8-Stroke Radicals"},
/*696,6*/ {"金","欽金龬龯龲"},
/*8,2*/ {"長","長"},
/*107,8*/ {"門","門𨳊𨳍𨳒"},
/*155,3*/ {"阜","䧑阜"},
/*3,2*/ {"隶","隶"},
/*47,2*/ {"隹","隹"},
/*106,3*/ {"雨","䨒雨"},
/*13,2*/ {"靑","靑"},
/*4,2*/ {"非","非"},
/*105,2*/ {"鱼","鱼"},
/*14,2*/ {"齿","齿"},
/*2552,82*/ {"Less common - Other","䤛䦇䦹䧒䨁䨓䲝𠁲𡑺𨤽𨦟𨱗𨳋𨳎𨳓𨸏𨹵𩄯𩽹𪚏𩇟鈸霣金露錄雷陋陵閭鍊鈴隸阮陸隆離隣降靖﨧難鉶"},
},
{{"Han 9-Stroke Radicals"},
/*7,2*/ {"面","面"},
/*98,2*/ {"革","革"},
/*27,2*/ {"韋","韋"},
/*6,2*/ {"韭","韭"},
/*16,4*/ {"音","竟音"},
/*117,3*/ {"頁","䪸頁"},
/*38,2*/ {"風","風"},
/*3,2*/ {"飛","飛"},
/*132,2*/ {"食","食"},
/*3,2*/ {"首","首"},
/*19,2*/ {"香","香"},
/*1932,60*/ {"Less common - Other","䉵䩂䪹䭫𠋑𠙬𠚑𡓷𤎂𥌕𥗶𧈐𩈃𩍼𩐁𩖘𩖱𩙱𩠐𩠯𩠱𩈚領類飯響韛"},
},
{{"Han 10-Stroke Radicals"},
/*194,4*/ {"馬","馬龭"},
/*48,2*/ {"骨","骨"},
/*7,2*/ {"高","高"},
/*70,2*/ {"髟","髟"},
/*10,2*/ {"鬥","鬥"},
/*3,2*/ {"鬯","鬯"},
/*10,2*/ {"鬲","鬲"},
/*30,2*/ {"鬼","鬼"},
/*1405,18*/ {"Less common - Other","䭴䯆𩍻𩡧𩨑駂駱驪鬒"},
},
{{"Han 11-Stroke Radicals"},
/*296,9*/ {"魚","䱽䲁䲅魚鷠龽𩶘"},
/*315,9*/ {"鳥","䲳䴈鳥鵥鷡鿂"},
/*9,2*/ {"鹵","鹵"},
/*38,2*/ {"鹿","鹿"},
/*18,3*/ {"麥","麥麧"},
/*4,3*/ {"麦","麦麸"},
/*8,2*/ {"麻","麻"},
/*1879,57*/ {"Less common - Other","䰲䱾䲂䲆䲥䲴䴉䴚𠧸𢉖𤋳𧖠𩖔𩵋𩶙𩾏𪇟𪉖𪌜𪎒鱀鸞魯鹿麗鱗鶴"},
},
{{"Han 12-Stroke Radicals"},
/*10,2*/ {"黃","黃"},
/*4,2*/ {"黍","黍"},
/*40,5*/ {"黑","墨黑黚"},
/*4,2*/ {"黹","黹"},
/*334,11*/ {"Less common - Other","䵊𢖛𪎳䵖黎"},
},
{{"Han 13-Stroke Radicals"},
/*13,3*/ {"黽","黽黿"},
/*4,3*/ {"黾","黾鼋"},
/*5,2*/ {"鼎","鼎"},
/*13,2*/ {"鼓","鼓"},
/*27,2*/ {"鼠","鼠"},
/*220,23*/ {"Less common - Other","䵶𡒡𡔷𥀻𪇞𪓑𪓼𪖀黾"},
},
{{"Han 14-Stroke Radicals"},
/*15,2*/ {"鼻","鼻"},
/*6,2*/ {"齊","齊"},
/*82,12*/ {"Less common - Other","䶊𠆜𪕿𪖐鼻齃"},
},
{{"Han 15-Stroke Radicals"},
/*45,2*/ {"齒","齒"},
/*214,11*/ {"Less common - Other","䶔𠎜𣦋𪗔𪘀"},
},
{{"Han 16-Stroke Radicals"},
/*11,4*/ {"龍","龍龑"},
/*3,2*/ {"龜","龜"},
/*68,13*/ {"Less common - Other","䶬䶯𪓻𪚑龜龍龜龎"},
},
{{"Han 17-Stroke Radicals"},
/*6,2*/ {"龠","龠"},
/*16,5*/ {"Less common - Other","䶳𪛊"},
},
{{"TODO"},
/*331,8*/ {"Missing","⺀⺛⼀々〻"},
},

  };
}
